language: php

sudo: false
install:
  - composer global require fabpot/php-cs-fixer
  - composer install
script:
  - vendor/bin/phpunit

php:
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - hhvm

notifications:
  email: false
